# Generated by Django 4.1.1 on 2023-02-10 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
