# Generated by Django 4.1.1 on 2023-02-11 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0002_admission_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='participating_students',
        ),
        migrations.RemoveField(
            model_name='assessment',
            name='score',
        ),
        migrations.RemoveField(
            model_name='takencourse',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='takencourse',
            name='ca2',
        ),
        migrations.RemoveField(
            model_name='takencourse',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='takencourse',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='takencourse',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='takencourse',
            name='total',
        ),
        migrations.CreateModel(
            name='WrittenAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(blank=True, default=0, null=True, verbose_name='Score')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='written_assessment', to='schoolapp.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolapp.student')),
            ],
        ),
    ]
