# Generated by Django 4.1.1 on 2023-02-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_remove_assessment_participating_students_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writtenassessment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_written_assessment', to='schoolapp.student'),
        ),
    ]
