# Generated by Django 4.1.1 on 2023-02-11 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_alter_writtenassessment_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='writtenassessment',
            name='semester',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.semester'),
            preserve_default=False,
        ),
    ]
