# Generated by Django 4.1.1 on 2023-02-11 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_writtenassessment_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='writtenassessment',
            name='written_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Written on'),
            preserve_default=False,
        ),
    ]
