# Generated by Django 4.1.1 on 2023-02-17 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0007_finalresult_delete_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='semester',
        ),
    ]
