# Generated by Django 4.1.1 on 2023-02-25 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0010_program_program_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finalresult',
            name='written_assessment',
        ),
    ]
