# Generated by Django 4.1.1 on 2023-02-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0011_remove_finalresult_written_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalresult',
            name='course',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='schoolapp.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='comment',
            field=models.CharField(blank=True, choices=[('PASS', 'PASS'), ('FAIL', 'FAIL')], editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('F', 'F')], editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='finalresult',
            name='total',
            field=models.FloatField(blank=True, editable=False, help_text='Adds All Assessments For the Current Semester', null=True),
        ),
    ]
