# Generated by Django 4.1.1 on 2023-03-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0012_finalresult_course_alter_finalresult_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='takencourse',
            name='registration_type',
            field=models.CharField(choices=[('Repeat Registration', 'Repeat Registration'), ('Normal Registration', 'Normal Registration')], default='Normal Registration', max_length=200),
        ),
    ]
